#!/bin/sh
# $1 = list of groups
# $2 = location of group folders
# $3 = number of the assignment

group_file=`cat $1 | grep -e '^\w' | sed -r 's/(^\w*).*/\1/g'`

for i in $group_file; do
    while true; do
	echo "Opening $i..."
	emacs $2/$i/$3/* $2/$i/$3/korrektur
	read -p "Are you done? [y/n] " yn
	case $yn in
	    [Yy]* ) break;;
	    * ) ;;
	esac
    done
done